import type { Amenity } from "./amenities.types";

export const AMENITIES: Amenity[] = [
  {
    id: "amenity-1",
    category: "ROOM",
    name: "King Size Bed",
    description: "Spacious king-size bed with premium bedding",
    icon: "BedDouble",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-2",
    category: "BATHROOM",
    name: "Rain Shower",
    description: "Modern rainfall shower with hot and cold water",
    icon: "ShowerHead",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-3",
    category: "FOOD",
    name: "Mini Bar",
    description: "In-room minibar with snacks and beverages",
    icon: "Wine",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-4",
    category: "ENTERTAINMENT",
    name: "Smart TV",
    description: "Smart TV with streaming and entertainment apps",
    icon: "Tv",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-5",
    category: "CONNECTIVITY",
    name: "Free Wi-Fi",
    description: "High-speed wireless internet access",
    icon: "Wifi",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-6",
    category: "COMFORT",
    name: "Air Conditioning",
    description: "Individually controlled air conditioning",
    icon: "Snowflake",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-7",
    category: "SAFETY",
    name: "In-Room Safe",
    description: "Secure electronic safe for valuables",
    icon: "LockKeyhole",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-8",
    category: "OTHER",
    name: "Room Service",
    description: "24/7 room service available",
    icon: "ConciergeBell",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-9",
    category: "ROOM",
    name: "Work Desk",
    description: "Dedicated workspace with comfortable seating",
    icon: "Laptop",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "amenity-10",
    category: "BATHROOM",
    name: "Hair Dryer",
    description: "Hair dryer available in the bathroom",
    icon: "Wind",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
