import type { RoomType, RoomTypeDetails } from "./roomTypes.types";

export const roomTypes: RoomType[] = [
  {
    id: "room-001",
    name: "Deluxe King Room",
    slug: "deluxe-king-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
      altText: "Deluxe king hotel room",
    },
    basePrice: 6500,
    currency: "INR",
    maxGuests: 3,
    adults: 2,
    children: 1,
    bedType: "KING",
    bedCount: 1,
    numberOfRooms: 8,
    amenities: [
      { name: "King Bed", icon: "BedDouble" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Mini Bar", icon: "Wine" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
      { name: "Work Desk", icon: "Laptop" },
      { name: "Rain Shower", icon: "ShowerHead" },
    ],
    isActive: true,
  },
  {
    id: "room-002",
    name: "Superior Queen Room",
    slug: "superior-queen-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80",
      altText: "Superior queen hotel room",
    },
    basePrice: 5200,
    currency: "INR",
    maxGuests: 2,
    adults: 2,
    children: 0,
    bedType: "QUEEN",
    bedCount: 1,
    numberOfRooms: 12,
    amenities: [
      { name: "Queen Bed", icon: "BedDouble" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "LED TV", icon: "Tv" },
      { name: "Tea & Coffee Maker", icon: "Coffee" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
      { name: "Hair Dryer", icon: "Wind" },
    ],
    isActive: true,
  },
  {
    id: "room-003",
    name: "Twin Deluxe Room",
    slug: "twin-deluxe-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80",
      altText: "Deluxe twin hotel room",
    },
    basePrice: 5800,
    currency: "INR",
    maxGuests: 2,
    adults: 2,
    children: 0,
    bedType: "TWIN",
    bedCount: 2,
    numberOfRooms: 10,
    amenities: [
      { name: "Twin Beds", icon: "BedDouble" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Tea & Coffee Maker", icon: "Coffee" },
      { name: "Work Desk", icon: "Laptop" },
      { name: "Rain Shower", icon: "ShowerHead" },
    ],
    isActive: true,
  },
  {
    id: "room-004",
    name: "Family Room",
    slug: "family-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
      altText: "Spacious family hotel room",
    },
    basePrice: 7800,
    currency: "INR",
    maxGuests: 5,
    adults: 3,
    children: 2,
    bedType: "QUEEN",
    bedCount: 2,
    numberOfRooms: 6,
    amenities: [
      { name: "Queen Bed", icon: "BedDouble" },
      { name: "Sofa Bed", icon: "Sofa" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Mini Fridge", icon: "Refrigerator" },
      { name: "Dining Area", icon: "Utensils" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
    ],
    isActive: true,
  },
  {
    id: "room-005",
    name: "Executive King Room",
    slug: "executive-king-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      altText: "Executive king hotel room",
    },
    basePrice: 8500,
    currency: "INR",
    maxGuests: 3,
    adults: 2,
    children: 1,
    bedType: "KING",
    bedCount: 1,
    numberOfRooms: 5,
    amenities: [
      { name: "King Bed", icon: "BedDouble" },
      { name: "High-Speed Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "55-inch Smart TV", icon: "Tv" },
      { name: "Mini Bar", icon: "Wine" },
      { name: "Espresso Machine", icon: "Coffee" },
      { name: "Work Desk", icon: "Laptop" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
      { name: "Rain Shower", icon: "ShowerHead" },
    ],
    isActive: true,
  },
  {
    id: "room-006",
    name: "Premium Suite",
    slug: "premium-suite",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80",
      altText: "Premium hotel suite with living area",
    },
    basePrice: 12500,
    currency: "INR",
    maxGuests: 4,
    adults: 2,
    children: 2,
    bedType: "KING",
    bedCount: 1,
    numberOfRooms: 4,
    amenities: [
      { name: "King Bed", icon: "BedDouble" },
      { name: "Separate Living Room", icon: "Sofa" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Mini Bar", icon: "Wine" },
      { name: "Coffee Machine", icon: "Coffee" },
      { name: "Bathtub", icon: "Bath" },
      { name: "Rain Shower", icon: "ShowerHead" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
    ],
    isActive: true,
  },
  {
    id: "room-007",
    name: "Standard Double Room",
    slug: "standard-double-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80",
      altText: "Standard double hotel room",
    },
    basePrice: 4200,
    currency: "INR",
    maxGuests: 2,
    adults: 2,
    children: 0,
    bedType: "DOUBLE",
    bedCount: 1,
    numberOfRooms: 15,
    amenities: [
      { name: "Double Bed", icon: "BedDouble" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "LED TV", icon: "Tv" },
      { name: "Tea & Coffee Maker", icon: "Coffee" },
      { name: "Hot Shower", icon: "ShowerHead" },
    ],
    isActive: true,
  },
  {
    id: "room-008",
    name: "Budget Single Room",
    slug: "budget-single-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      altText: "Comfortable single hotel room",
    },
    basePrice: 2800,
    currency: "INR",
    maxGuests: 1,
    adults: 1,
    children: 0,
    bedType: "SINGLE",
    bedCount: 1,
    numberOfRooms: 10,
    amenities: [
      { name: "Single Bed", icon: "BedSingle" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "LED TV", icon: "Tv" },
      { name: "Work Desk", icon: "Laptop" },
      { name: "Hot Shower", icon: "ShowerHead" },
    ],
    isActive: true,
  },
  {
    id: "room-009",
    name: "Bunk Family Room",
    slug: "bunk-family-room",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
      altText: "Family hotel room with bunk beds",
    },
    basePrice: 5600,
    currency: "INR",
    maxGuests: 4,
    adults: 2,
    children: 2,
    bedType: "BUNK",
    bedCount: 2,
    numberOfRooms: 5,
    amenities: [
      { name: "Bunk Beds", icon: "BedDouble" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Mini Fridge", icon: "Refrigerator" },
      { name: "Storage Locker", icon: "Lock" },
      { name: "Dining Area", icon: "Utensils" },
    ],
    isActive: true,
  },
  {
    id: "room-010",
    name: "King Suite with Sofa Bed",
    slug: "king-suite-sofa-bed",
    primaryImage: {
      url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
      altText: "King suite with sofa bed and living area",
    },
    basePrice: 10500,
    currency: "INR",
    maxGuests: 4,
    adults: 2,
    children: 2,
    bedType: "SOFA_BED",
    bedCount: 2,
    numberOfRooms: 4,
    amenities: [
      { name: "King Bed", icon: "BedDouble" },
      { name: "Sofa Bed", icon: "Sofa" },
      { name: "Living Area", icon: "Armchair" },
      { name: "Free Wi-Fi", icon: "Wifi" },
      { name: "Air Conditioning", icon: "Snowflake" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Mini Bar", icon: "Wine" },
      { name: "Coffee Machine", icon: "Coffee" },
      { name: "Bathtub", icon: "Bath" },
      { name: "Electronic Safe", icon: "LockKeyhole" },
    ],
    isActive: true,
  },
];

export const roomTypeDetails: RoomTypeDetails = {
  id: "room-001",
  name: "Deluxe King Room",
  slug: "deluxe-king-room",
  description:
    "A spacious and elegantly furnished king room featuring premium bedding, a comfortable work area, and modern amenities. Ideal for couples and business travelers.",
  images: [
    {
      id: "room-001-img-01",
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=85",
      altText: "Deluxe king hotel room with modern furnishings",
      isPrimary: true,
      sortOrder: 1,
    },
    {
      id: "room-001-img-02",
      url: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1600&q=85",
      altText: "Comfortable hotel bed in deluxe room",
      isPrimary: false,
      sortOrder: 2,
    },
    {
      id: "room-001-img-03",
      url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1600&q=85",
      altText: "Modern hotel bathroom",
      isPrimary: false,
      sortOrder: 3,
    },
  ],
  maxGuests: 3,
  adults: 2,
  children: 1,
  sizeSqFt: 420,
  basePrice: 6500,
  currency: "INR",
  bedType: "KING",
  bedCount: 1,
  smokingAllowed: false,
  petsAllowed: false,
  isActive: true,
  amenities: [
    { name: "King Bed", icon: "BedDouble" },
    { name: "Free Wi-Fi", icon: "Wifi" },
    { name: "Air Conditioning", icon: "Snowflake" },
    { name: "Smart TV", icon: "Tv" },
    { name: "Mini Bar", icon: "Wine" },
    { name: "Electronic Safe", icon: "LockKeyhole" },
    { name: "Work Desk", icon: "Laptop" },
    { name: "Rain Shower", icon: "ShowerHead" },
  ],
  roomCount: 8,
  roomStatusSummary: {
    total: 8,
    active: 8,
    occupancy: {
      available: 5,
      occupied: 2,
      other: 1,
    },
    housekeeping: {
      clean: 5,
      dirty: 1,
      inspected: 1,
      inProgress: 1,
      other: 0,
    },
  },
  createdAt: new Date("2025-01-15T09:00:00Z"),
  updatedAt: new Date("2026-09-28T11:30:00Z"),
};
